const INIT_BLOGS = 'INIT_BLOGS';
const SET_NOTIFICATION = 'SET_NOTIFICATION';
const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
const NEW_BLOG = 'NEW_BLOG';
const DELETE_BLOG = 'DELETE_BLOG';
const LIKE_BLOG = 'LIKE_BLOG';
const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
const FAILED_LOGIN = 'FAILED_LOGIN';
const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
const GET_ALL_USERS = 'GET_ALL_USERS';

export default {
  INIT_BLOGS,
  HIDE_NOTIFICATION,
  SET_NOTIFICATION,
  NEW_BLOG,
  DELETE_BLOG,
  LIKE_BLOG,
  LOGIN_SUCCEEDED,
  FAILED_LOGIN,
  USER_LOGGED_OUT,
  GET_ALL_USERS,
};
